# Generated by Django 5.2.9 on 2025-12-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TourismCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tourism Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief one-liner description", max_length=200
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "entry_fee",
                    models.CharField(
                        blank=True, help_text="e.g., 'Free' or '₹50'", max_length=100
                    ),
                ),
                (
                    "timings",
                    models.CharField(
                        blank=True, help_text="e.g., '9 AM - 6 PM'", max_length=200
                    ),
                ),
                ("best_time_to_visit", models.CharField(blank=True, max_length=100)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured/popular section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attractions",
                        to="api.area",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attractions",
                        to="api.tourismcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
    ]
