# Generated by Django 5.2.9 on 2025-12-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_area_tourismcategory_attraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelplineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority shows first"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Helpline Categories",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Helpline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("alternate_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional information about the service"
                    ),
                ),
                (
                    "timings",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '24/7' or '9 AM - 5 PM'",
                        max_length=200,
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False, help_text="24/7 emergency service"
                    ),
                ),
                ("is_toll_free", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helplines",
                        to="api.area",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helplines",
                        to="api.helplinecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_emergency", "category__priority", "name"],
            },
        ),
    ]
